export const fetchCurrentUser = jest.fn(() => Promise.resolve())
export const login = jest.fn(() => Promise.resolve())
export const logout = jest.fn(() => Promise.resolve())
export const register = jest.fn(() => Promise.resolve())
export const requestPasswordReset = jest.fn(() => Promise.resolve())
export const resetPassword = jest.fn(() => Promise.resolve())
